language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "nightly"
install:
    - python setup.py install
    - pip install codecov
    - pip install pytest-cov
script:
    - py.test --cov=nncell tests
after_success:
    - codecov
